/** Maps a `stack` entry (frontmatter) to its logo asset. Tools without an entry render without a logo. */
export const TOOL_LOGOS: Record<string, string> = {
  'Relevance AI': '/logos/relevanceai.png',
  Slack: '/logos/slack.png',
  Zapier: '/logos/zapier.png',
  Make: '/logos/make.png',
  Apollo: '/logos/apollo.png',
  Apify: '/logos/apify.svg',
  Salesforce: '/logos/salesforce.png',
  'Google Sheets': '/logos/googlesheets.png',
  'Google Drive': '/logos/googledrive.png',
  Outreach: '/logos/outreach.png',
  Obsidian: '/logos/obsidian.svg',
  'Claude Code': '/logos/claude.png',
  Cursor: '/logos/cursor.png',
  OpenAI: '/logos/openai.svg',
  'OpenAI API': '/logos/openai.svg',
  'Next.js': '/logos/nextjs.svg',
  TypeScript: '/logos/typescript.svg',
  Supabase: '/logos/supabase.svg',
  'Drizzle ORM': '/logos/drizzle.svg',
  Swift: '/logos/swift.svg',
  ElevenLabs: '/logos/elevenlabs.svg',
};
